server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    # 值为false意味着自身仅作为服务器，不作为客户端
    register-with-eureka: false
    # 值为false意味着无需注册自身
    fetch-registry: false
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false

