server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false

